feat: analyze user behavior across different lending protocols
CarmineOptions/derisk-research pull request #107
Opened 2024-05-27 19:57 UTC by NueloSE

The following checks have been cover in this analysis:
- [x] Answer required questions from the setup.
- [x] Has been properly documented.
- [x] The analysis provides meaningful outputs.
- [x] All code runs correctly.

2024-05-29 23:42 UTC, lukaspetrasek commented
Hi, please remove the output of the notebook.

2024-05-30 00:14 UTC, NueloSE commented
> Hi, please remove the output of the notebook.

@lukaspetrasek removed the output should i also remove the result interpretations?

2024-05-31 00:07 UTC, lukaspetrasek commented
> > Hi, please remove the output of the notebook.
> 
> @lukaspetrasek removed the output should i also remove the result interpretations?

No, keep it like this. It's just that with the outputs, it's a little harder to review the ntb.

2024-06-02 21:08 UTC, lukaspetrasek requested changes
@NueloSE Reviewed.

2024-06-02 21:08 UTC, lukaspetrasek commented on notebooks/Analyze_user_behavior_across_different_lending_protocols.ipynb
> +    "#### Data Visualization"
Could you add Venn diagrams to visualize the USD amounts as well?

2024-06-04 14:27 UTC, lukaspetrasek commented
Hi @NueloSE ,

We'll be merging this PR so that it counts towards the OD Hackaton. You will receive a partial reward, but we'll be happy if you open a new PR and finish the task!

2024-06-04 14:28 UTC, merged