Distinguish available liquidity per swap amm
CarmineOptions/derisk-research pull request #120
Opened 2024-05-30 16:53 UTC by adrianvrj

Closes #111 

Current output

![telegram-cloud-photo-size-1-5100694837539220366-y](https://github.com/CarmineOptions/derisk-research/assets/111903096/c032d6e1-9c8c-4b86-b0ff-22dc3ed51a82)

2024-06-02 22:22 UTC, lukaspetrasek commented
> Closes #111
> 
> Current output
> 
> ![telegram-cloud-photo-size-1-5100694837539220366-y](https://private-user-images.githubusercontent.com/111903096/335309822-c032d6e1-9c8c-4b86-b0ff-22dc3ed51a82.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjM5MDYsIm5iZiI6MTcxNzM2MzYwNiwicGF0aCI6Ii8xMTE5MDMwOTYvMzM1MzA5ODIyLWMwMzJkNmUxLTljOGMtNGI4Ni1iMGZmLTIyZGMzZWQ1MWE4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQyMTI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODkzZmRmZTllMzEwMWFmZTIyNzRjZGNjY2RmM2VkNjBhZTYwMzhkMWRjMGQ4NTczZGI2MDc4NTBmZWY1MDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t3v5wEz3Ekhmjhp0PRKK_lFQWqCKlCihCTaPv0_o60s)

Looking at the chart, the values are too large. Each bar should roughly correspond to tens of thousands of dollars, so the scale of 10^15 is too high. Please investigate whether you're working with the decimals correctly, or whether you're not adding the liquidity multiple times.

2024-06-02 22:22 UTC, lukaspetrasek requested changes

2024-06-02 22:22 UTC, lukaspetrasek commented on src/main_chart.py
> +            supply = swap_amms.get_supply_at_price(collateral_token, price, debt_token, amm)
Add variable names to the call to `get_supply_at_price`.

2024-06-02 22:22 UTC, lukaspetrasek commented on src/main_chart.py
> +            data.at[index, f"{amm}_debt_token_supply"] = supply
Use `data['collateral_token_price'].apply` instead of the for loop.

2024-06-02 22:22 UTC, lukaspetrasek commented on src/main_chart.py
> +        data.at[index, "debt_token_supply"] = total_supply
This can be the sum over the 4 AMM columns.

2024-06-02 22:22 UTC, lukaspetrasek commented on src/main_chart.py
> +    color_map = {"jedi": "#ECD662", "10k": "#4CA7D0", "my": "#76C1FA", "sith": "#FFA07A"}
Use different shades of blue, to be consistent with the current version of the chart.

2024-06-02 22:22 UTC, lukaspetrasek commented on src/main_chart.py
> +    amms = ["jedi", "10k", "my", "sith"]
This could be a constant in the `swap_amm.py` module.

2024-06-02 22:22 UTC, lukaspetrasek commented on src/main_chart.py
> +        color_discrete_map={**color_map, "liquidable_debt_at_interval": "#FFD700"},
Pls keep the TODO comment in place.

2024-06-02 22:22 UTC, lukaspetrasek commented on src/swap_amm.py
> +        for amm, addresses in self.addresses_dict.items():
`addresses` is always a single address, right?
```suggestion
        for amm, address in self.addresses_dict.items():
```

2024-06-02 22:22 UTC, lukaspetrasek commented on src/swap_amm.py
> +                    balance += myswap_pool[token.symbol.upper()]
This always adds the `MySwap` balance even if `amm` is not `MySwap`.

2024-06-02 22:22 UTC, lukaspetrasek commented on src/swap_amm.py
> +                token.balance_base = sum(self.balances[amm][token.symbol] for amm in self.balances)
It's not necessary to perform this in every iteration.

2024-06-04 01:25 UTC, lukaspetrasek commented on src/swap_amm.py
> +
Add two more blank lines 🙏🏼

2024-06-04 01:25 UTC, lukaspetrasek commented on src/main_chart.py
>      figure = plotly.express.bar(
I'm still getting this error.

2024-06-04 01:28 UTC, adrianvrj commented on src/swap_amm.py
> +
No problem! :)

2024-06-04 01:28 UTC, adrianvrj commented on src/main_chart.py
>      figure = plotly.express.bar(
I'll take a closer look at that

2024-06-04 01:31 UTC, lukaspetrasek commented on src/swap_amm.py
>      def buy_tokens(self, symbol, amount):
Pls add typing.

2024-06-04 01:31 UTC, lukaspetrasek commented on src/main_chart.py
> +import pandas
Keeping unresolved.

2024-06-04 01:32 UTC, lukaspetrasek commented on src/main_chart.py
> +            supply = swap_amms.get_supply_at_price(collateral_token, price, debt_token, amm)
Keeping unresolved.

2024-06-04 01:41 UTC, lukaspetrasek requested changes

2024-06-04 01:41 UTC, lukaspetrasek commented on src/swap_amm.py
>                      balance += myswap_pool[token.symbol.upper()]
Now MySwap is still added twice, right? First on line 330, and then on line 332.

2024-06-04 01:41 UTC, lukaspetrasek commented on src/swap_amm.py
> +                token.balance_converted = balance
Remove one of the field for balance then. And name the remaining one just `balance`.

2024-06-04 01:41 UTC, lukaspetrasek commented on src/swap_amm.py
> +                token.balance_converted = balance
This gets overwritten at each iteration, so only the value for the last amm survives.

2024-06-04 15:23 UTC, lukaspetrasek commented
Merged 🙏🏼

2024-06-04 15:24 UTC, merged