Liquidator analysis
CarmineOptions/derisk-research pull request #126
Opened 2024-06-02 10:15 UTC by james001-c

kindly review

2024-06-04 01:11 UTC, lukaspetrasek requested changes

2024-06-04 01:11 UTC, lukaspetrasek commented on notebooks/Liquidators_analysis.ipynb
> +    "liquidators_loan_counts = ep_data.groupby('from_address')['transaction_hash'].nunique().reset_index()\n",
No, this is the number of transactions per smart contract.

2024-06-04 01:11 UTC, lukaspetrasek commented on notebooks/Liquidators_analysis.ipynb
> +    "# Group by 'User' and 'Protocol' to get the number of liquidators per protocol\n",
Hint: Check the values of the `key_name` column in the data. You'll find some liquidation events there.

2024-06-04 01:11 UTC, lukaspetrasek commented on notebooks/Liquidators_analysis.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABKYAAAMWCAYAAADLc44dAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOz
I see a lot of cells likely used for debugging below this one. Pls remove them, or add some comments explaining why do we need to keep these cells.

2024-06-04 01:11 UTC, lukaspetrasek commented on notebooks/Liquidators_analysis.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABKYAAAMWCAYAAADLc44dAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOz
The rest of the analysis is completely wrong. Do not hesitate to ask if you don't know something 😉

2024-06-04 01:11 UTC, lukaspetrasek commented on notebooks/Liquidators_analysis.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABKYAAAMWCAYAAADLc44dAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOz
Compute the amount of liquidated debt like this:
1) Identify only liquidation events. Use Starkscan to explore their structure.
2) Identify the amounts of debt tokens liquidated. Optionally, analyze the collateral tokens liquidated for extra points 🥇
3) Compute aggregate states, like total volumes liquidated, total amounts per token, average liquidated amounts, etc.
4) [Optional] Fetch prices for these tokens (in USD). E.g. from Coingecko.
5) [Optional] Multiply the token amount by the corresponding prices.
6) Repeat task 3) for the USD amounts.

2024-06-04 14:37 UTC, lukaspetrasek commented
Hi @james001-c  ,

We'll be merging this PR so that it counts towards the OD Hackaton. You will receive a partial reward, but we'll be happy if you open a new PR and finish the task!

2024-06-04 14:42 UTC, merged

2024-06-11 14:22 UTC, james001-c commented
Hello CarmineOptions/derisk-research

I stopped working because you dropped a message on the telegram account
that you were going to merge the work so I thought I lost already. Please
kindly re-assign me.

On Tue, 4 Jun 2024, 15:42 lukaspetrasek, ***@***.***> wrote:

> Merged #126 <https://github.com/CarmineOptions/derisk-research/pull/126>
> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CarmineOptions/derisk-research/pull/126#event-13037679570>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARPUXTMCDZASZTJNKTX32WDZFXG5NAVCNFSM6AAAAABIU53IIOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTGAZTONRXHE2TOMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>