Order book for Uniswap V2 AMMs
CarmineOptions/derisk-research pull request #127
Opened 2024-06-03 11:20 UTC by faurdent

2024-06-03 11:50 UTC, faurdent commented
To test contents:
cd data_handler
poetry install
poetry shell
python ./order_books_tests.py

2024-06-03 16:29 UTC, lukaspetrasek commented
@faurdent Replied on TG.

2024-06-03 22:08 UTC, lukaspetrasek requested changes

2024-06-03 22:08 UTC, lukaspetrasek commented on data_handler/handlers/order_books/ekubo/histogram.py
> +def fetch_order_book_and_current_price(token_a: str, token_b: str) -> tuple:
Pls add types of individual items in the tuple. Holds for all other occurrences, and also for `dict`, `list`, `set`, etc.

2024-06-03 22:08 UTC, lukaspetrasek commented on data_handler/handlers/order_books/uniswap_v2/jediswap.py
> +import asyncio
This code is experimental? Does it work? Feels like `JediSwap` is covered in the `main`.

2024-06-04 14:12 UTC, lukaspetrasek requested changes

2024-06-04 14:12 UTC, lukaspetrasek commented on data_handler/handlers/order_books/uniswap_v2/main.py
> +        min_price = current_price - (current_price * price_change_ratio)
```suggestion
        min_price = (decimal.Decimall("1") - price_change_ratio) * current_price
```

2024-06-04 14:12 UTC, lukaspetrasek commented on data_handler/handlers/order_books/uniswap_v2/main.py
> +    token_amount = order_book.calculate_token_amount_price_change(Decimal("3750"), Decimal(0.05))
The current price should be derived from the orderbook. It's the mid price between the best bid and ask.

2024-06-04 14:14 UTC, djeck1432 commented on data_handler/celery_app/celery_conf.py
> +    uniswap_v2_order_book,
these tasks should be run first manually and then could be uncommented

2024-06-04 15:49 UTC, lukaspetrasek commented
Hi @faurdent  ,

We'll be merging this PR so that it counts towards the OD Hackaton. You will receive a partial reward, but we'll be happy if you open a new PR and finish the task!

2024-06-04 15:57 UTC, merged