feat: update standardize protocols
CarmineOptions/derisk-research pull request #142
Opened 2024-06-15 19:19 UTC by godekina

Hi @lukaspetrasek this PR is a continuation of the merged PR at https://github.com/CarmineOptions/derisk-research/pull/123/commits/cca054223b929abc9c06b1b8e6ee1501f9f623c7 
I have added code to standardize events data for all other protocols in addition to zklend.

kindly review.

2024-06-19 14:18 UTC, lukaspetrasek requested changes

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "# Dictionary of Parquet URLs\n",
Pls use the same method for loading data as here: https://github.com/CarmineOptions/derisk-research/blob/master/notebooks/Liquidators_data.ipynb (cell 2). No need to use `gcsfs`.

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
>      "pd.set_option('display.max_colwidth', None)\n",
Move this setup to the first cell.

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "    return value.decode(\"utf-8\")  "
Do you need a function for this? Isn't it simpler to use the `decode` method directly?

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "        else:\n",
What are the other key names that we ignore?

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "        else:\n",
What are the other key names that we ignore? For example, `Burn` events are missing.

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "        if row['key_name'] == 'Mint':\n",
From this, we don't know whether the `Mint` event represents a deposit or borrowing event. Pls add that information by mapping `token` on the type of token defined here: https://github.com/CarmineOptions/derisk-research/blob/master/src/nostra_alpha.py#L36.

For example, `Mint` events for `non_interest_bearing_collateral` or `interest_bearing_collateral` are deposit events, for `debt` they're borrowing events, etc. Map the event type names on those used for zkLend.

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "        else:\n",
What are the other key names that we ignore?

2024-06-19 14:18 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "        else:\n",
What are the other key names that we ignore?

2024-08-14 13:01 UTC, lukaspetrasek requested changes

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "## 2. Define a Function to Transform Each Row\n",
```suggestion
    "## 2. Define a function to transform each row\n",
```

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "            raise ValueError(\"Unrecognized key_name\") # Raising an error for unrecognized key_name\n",
Print the key name that was not recognized when raising the error.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "        raise RuntimeError(f\"Failed to extract data from row: {str(e)}\") from e\n",
```suggestion
    "        raise ValueError(f\"Failed to extract data from row: {str(e)}\") from e\n",
```

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "    token_type = NOSTRA_ALPHA_TOKENS_TO_TOKEN_TYPES.get(token_address.lower())\n",
Why `.lower()`? That shouldn't make any difference.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "    return 'interest_rate_updated'  # Default to 'interest rate updated' if not matched\n",
The default should be raising an error (if no match is found). An `interest_rate_updated` should be returned when `token_address` is `0x03d39f7248fb2bfb960275746470f7fb470317350ad8656249ec66067559e892` and `key_name` is `InterestStateUpdated`.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
>      "nostra_alpha_data = df_events[df_events['Protocol'] == 'nostra_alpha']\n",
```suggestion
    "nostra_alpha_events = df_events[df_events['Protocol'] == 'nostra_alpha']\n",
```
In general, it's best to be more descriptive whenever you can. `Data` is very general, `events` is specific.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
>      "hashstack_v1_data = df_events[df_events['Protocol'] == 'hashstack_v1']\n",
```suggestion
    "hashstack_v1_events = df_events[df_events['Protocol'] == 'hashstack_v1']\n",
```

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "zklend_events = df_events[df_events['Protocol'] == 'zklend']\n",
```suggestion
    "zklend_events = events[events['Protocol'] == 'zklend']\n",
```
No need to put `df` (i.e. the type of the variable) in the name.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "def extract_nostra_alpha(row: pd.Series) -> pd.Series:\n",
```suggestion
    "def standardize_nostra_alpha_event(row: pd.Series) -> pd.Series:\n",
```

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> -    "# Display the resulting dataframe\n",
Why remove the display here and not in the case of other protocols?

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "standardized_hashstack_v0_events = hashstack_v0_data.apply(standardize_hashstack_v0_event, axis=1)\n",
I'm gettings `RuntimeError: Failed to extract data from row: list index out of range` here.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "standardized_hashstack_v1_events = hashstack_v1_data.apply(standardize_hashstack_v1_event, axis=1)\n",
I'm getting `RuntimeError: Failed to extract data from row: Unrecognized key_name` here.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> -    "        else:\n",
Fix the indent, this throws a SyntaxError now.

2024-10-01 21:51 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
>    {
The code for Nostra Mainnet should be adjusted according to the comments above as well. Moreover, you need to copy the setting for `NOSTRA_MAINNET_TOKENS_TO_TOKEN_TYPES` and `NOSTRA_MAINNET_TOKEN_TYPES_TO_EVENT_TYPES` from `src`.

2024-10-04 01:32 UTC, godekina commented
@lukaspetrasek all changes requested were made to the notebook, kindly review: 
https://github.com/CarmineOptions/derisk-research/pull/142/commits/6308af629567516188ac87e42dd3aea7f38ce602

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "## 1.  Load event data  the paraquet file"
```suggestion
    "## 1.  Load event data from the paraquet file"
```

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "## 2. Define a function to transform Each Row\n",
```suggestion
    "## 2. Define a function to transform each row\n",
```

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "def extract_zklend(row: pd.Series) -> pd.Series:\n",
```suggestion
    "def standardize_zklend_event(row: pd.Series) -> pd.Series:\n",
```

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +   "execution_count": 19,
Move `Nostra Mainnet` right below `Nostra Alpha`.

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "NOSTRA_ALPHA_TOKENS_TO_TOKEN_TYPES :dict[str, str] =  { \n",
```suggestion
    "NOSTRA_ALPHA_TOKENS_TO_TOKEN_TYPES: dict[str, str] =  { \n",
```

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "NOSTRA_ALPHA_TOKEN_TYPES_TO_EVENT_TYPES : dict[str, str] = {\n",
```suggestion
    "NOSTRA_ALPHA_TOKEN_TYPES_TO_EVENT_TYPES: dict[str, str] = {\n",
```

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
>      "def extract_nostra_alpha(row: pd.Series) -> pd.Series:\n",
```suggestion
    "def standardize_nostra_alpha_event(row: pd.Series) -> pd.Series:\n",
```

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
>      "                'timestamp': data_list[15]\n",
There's a lot of variables that we actually don't need. Check src.hashstack_v0.py to see what's needed and what's not needed. Ignore variables which are not needed. Holds for Hashstack V1, too.

2024-10-08 00:55 UTC, lukaspetrasek commented on notebooks/standardize_events_data.ipynb
> +    "def extract_nostra_mainnet(row: pd.Series) -> pd.Series:\n",
```suggestion
    "def standardize_nostra_mainnet_event(row: pd.Series) -> pd.Series:\n",
```

2024-10-08 18:11 UTC, merged