Harmonize colors on the dashboard
CarmineOptions/derisk-research pull request #197
Opened 2024-10-01 16:55 UTC by martinvibes

@djeck1432 Kindly review the changes made.

2024-10-02 10:27 UTC, djeck1432 requested changes

2024-10-02 10:27 UTC, djeck1432 commented on app.py
> +color_map = {
1. Constant should CAPITALIZE 
`COLORS_MAP`

2024-10-03 09:01 UTC, martinvibes commented
@djeck1432 kindly review

2024-10-03 18:35 UTC, djeck1432 requested changes
Please, take a look to this picture, you didn't change color here, still the same:
1. supply and demand in the main chart by their color,
<img width="1434" alt="Screenshot 2024-10-03 at 20 31 32" src="https://github.com/user-attachments/assets/43f73ad6-09ea-44d6-9198-54d861a46cd5">
 It should be different color per `supply` `collateral` `debt`
 
 Please, read issue again, there are 3 points which you should complete

2024-10-03 18:35 UTC, djeck1432 commented on app.py
> +            color_discrete_sequence=[color_map.get('Collateral')],
You changed `COLORS_MAP` but didn't change `color_map`
```suggestion
            color_discrete_sequence=[COLORS_MAP.get('Collateral')],
```

2024-10-03 18:35 UTC, djeck1432 commented on app.py
> +            color_discrete_sequence=[color_map.get('Debt')],
The same here 
```suggestion
            color_discrete_sequence=[COLORS_MAP.get('Debt')],
```

2024-10-06 07:33 UTC, closed without merging