feat: harmonize colors on dashboard
CarmineOptions/derisk-research pull request #208
Opened 2024-10-06 07:32 UTC by martinvibes

hello @djeck1432 please kindly review :)

2024-10-06 08:56 UTC, djeck1432 requested changes

2024-10-06 08:56 UTC, djeck1432 commented on app.py
> -    if loan.empty:
Why did you remove this `if loan.empty`?

2024-10-06 08:56 UTC, djeck1432 commented on app.py
> +COLORS_MAP = {
You created this class and use only `Collateral` and `Debt` why do you need others key:value?

2024-10-07 05:08 UTC, martinvibes commented
hello @djeck1432 i have implemented requested changes 
Kindly review :)

2024-10-07 10:08 UTC, djeck1432 commented
<img width="802" alt="Screenshot 2024-10-07 at 12 07 47" src="https://github.com/user-attachments/assets/c7747cc7-d785-42e9-a2c2-96b12396a312">
Hi, while running your code, I got this error, please fix that

2024-10-08 17:37 UTC, closed without merging