Created underlying token symbols next to the token address on the das…
CarmineOptions/derisk-research pull request #216
Opened 2024-10-17 22:42 UTC by josephchimebuka

Fixs #188

2024-10-18 07:06 UTC, djeck1432 requested changes

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +from typing import Dict, Set
Please, run `isort` command https://pycqa.github.io/isort/ for this file
p.s. this package is already install, just run command to format `imports`

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +def fetch_token_symbols2(token_addresses: Set[str]) -> Dict[str, str]:
add docstring please

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +def fetch_token_symbols2(token_addresses: Set[str]) -> Dict[str, str]:
Why do you have `fetch_token_symbols2` 
Let's come up with better naming

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +async def get_underlying_token_symbol(token_address: str) -> str:
I think it should be in `chart_utils.py` not here
Also add docstring

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +    except Exception:
Be more specific in `Exception` which you are trying to catch

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +        return underlying_token_symbol.strip('\x00')
Please, move it to `constant` variable `'\x00'`
In python it's call magic string read more here: https://softwareengineering.stackexchange.com/questions/365339/what-is-wrong-with-magic-strings

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +def extract_token_addresses(loans_data: pandas.DataFrame) -> Set[str]:
add docstring

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +def update_loan_data_with_symbols(loans_data: pandas.DataFrame, token_symbols: Dict[str, str]) -> pandas.DataFrame:
add docstring

2024-10-18 07:06 UTC, djeck1432 commented on app.py
> +    loans_data['Collateral'] = loans_data['Collateral'].apply(update_column)
Please, run `black` command to have proper formattting

2024-10-22 02:42 UTC, josephchimebuka commented
Hello @djeck1432 and @lukaspetrasek pls can you help me review my code I've made the requested changes

2024-10-23 08:50 UTC, djeck1432 commented
While testing your PR, I had next error, please fix it:

```
starknet_py.net.client_errors.ClientError: Client failed with code 40. Message: Contract error. Data: {'revert_error': 'Entry point EntryPointSelector(0x12d60825cc57ee4a44efdb81f0050fb99bcc550c411acb3ca38c9b83103dc2f) not found in contract.'}

```
in `fetch_token_symbols_from_set_of_loan_addresses`

@josephchimebuka

2024-10-24 22:39 UTC, josephchimebuka commented
Hello @djeck1432 I have fix changes and it is running on local as well

2024-10-26 10:53 UTC, djeck1432 requested changes

2024-10-26 12:02 UTC, josephchimebuka commented
Used isort should be better now @djeck1432

2024-10-27 20:21 UTC, djeck1432 requested changes
Please, sync with master branch

2024-10-27 20:21 UTC, djeck1432 commented on app.py
> +
remove blank lines
better will be if you use `black` command for this file

2024-10-28 15:21 UTC, djeck1432 approved these changes

2024-10-28 15:21 UTC, djeck1432 approved these changes
Looks godo to me

2024-10-28 15:31 UTC, merged