Standardize event data for accumulators’ data
CarmineOptions/derisk-research pull request #224
Opened 2024-10-23 21:19 UTC by Gerson2102

Adding the functionality to standardize. Resolves this #220.

2024-10-24 07:14 UTC, Gerson2102 commented on data_handler/handler_tools/data_parser/serializers.py
> +class AccumulatorsSyncEvent(BaseModel):
Got it, can you give an example? Maybe DataSyncEvent?

2024-10-24 07:15 UTC, Gerson2102 commented on data_handler/handlers/loan_states/zklend/events.py
> +        parsed_event = ZklendDataParser.parse_accumulators_sync_event(event["data"])
I dont get this, can you elaborate more?

2024-10-24 07:25 UTC, djeck1432 commented on data_handler/handler_tools/data_parser/zklend.py
> +            lending_accumulator=Decimal(int(event_data[1], 16)) / Decimal("1e27"),
Here is docs about validator in pydantic
https://docs.pydantic.dev/latest/concepts/validators/#annotated-validators

this part should be in field_validator in your pydantic models
`Decimal(int(event_data[1], 16)) / Decimal("1e27"),`
so you will do next:
```
AccumulatorsSyncEvent(lending_accumulator=event_data[1])
and in `AccumulatorsSyncEvent.validate_fields` will be the logic of it `Decimal(int(event_data[1], 16)) / Decimal("1e27"),`

p.s. it's example of code

2024-10-24 07:26 UTC, djeck1432 commented on data_handler/handlers/loan_states/zklend/events.py
> +        parsed_event = ZklendDataParser.parse_accumulators_sync_event(event["data"])
add to the end of the variable name, `_data`
`parsed_event` + `_data`

2024-10-24 20:04 UTC, djeck1432 commented
@Gerson2102 Cool, will check it tomorrow

2024-10-25 08:43 UTC, djeck1432 requested changes

2024-10-25 08:43 UTC, djeck1432 commented on data_handler/handler_tools/data_parser/serializers.py
> +    def hex_to_decimal(cls, v):
add docstring and annotation type and return type

2024-10-25 13:04 UTC, Gerson2102 commented
Done here mate @djeck1432

2024-10-25 20:52 UTC, djeck1432 approved these changes
Looks good to me

2024-10-25 20:53 UTC, merged