test: DeRiskAPIConnector initializes and gets data
CarmineOptions/derisk-research pull request #229
Opened 2024-10-24 12:42 UTC by ooochoche

Closes #222 

The new changes implemented in [test_api_connector.py](https://github.com/ooochoche/derisk-research/blob/master/data_handler/tests/test_api_connector.py) implements test for the following
- DeRiskConnector Initializes successfully when the DERISK_API_URL environment variable is provided
- DeRiskConnector throws a ValueError when the DERISK_API_URL environment variable is not provided
- DeRiskConnector gets and returns data successfully
- DeRiskConnector fails to return any data

2024-10-24 20:19 UTC, djeck1432 requested changes

2024-10-24 20:19 UTC, djeck1432 commented on data_handler/tests/test_api_connector.py
> +        self.assertEqual(connector.api_url, "https://api.derisk.io")
Move it to constant, Don't repeat yourself
`https://api.derisk.io`

2024-10-24 20:19 UTC, djeck1432 commented on data_handler/tests/test_api_connector.py
> +            result = connector.get_data(
please, add more test invalid data to make sure that we handle any error
Imagine, that `min_block_number` is None or string
or `from_address` is None

2024-10-25 20:51 UTC, djeck1432 commented
@ooochoche Please, update your PR

2024-10-25 20:53 UTC, ooochoche commented
Alright sure I will thanks

2024-10-25 22:51 UTC, ooochoche commented
Hello @djeck1432 You can review the update to the PR, thank you.

2024-10-26 10:09 UTC, djeck1432 approved these changes
Looks good to me

2024-10-26 10:09 UTC, merged