Database test
CarmineOptions/derisk-research pull request #231
Opened 2024-10-25 09:58 UTC by NueloSE

Fixes #227 

mock database and InitializerDBConnector are ready for review still workin on DBConnector

2024-10-25 09:59 UTC, djeck1432 commented
@NueloSE Okay, thank you for update

2024-10-25 20:57 UTC, djeck1432 requested changes

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/conftest.py
> +    return DBConnector(db_url="sqlite:///:memory:")
Please, don't use any db, just simple mock database connection,  example of how to do it
https://github.com/djeck1432/spotnet/blob/main/web_app/tests/conftest.py

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_write_to_db(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def db_connector(self):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +        loan_state = LoanState(
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_delete_object(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_get_latest_block(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_write_batch_to_db(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_get_latest_order_book(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_get_unique_users_last_block_objects(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_get_last_interest_rate_record_by_protocol_id(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_get_interest_rate_by_block(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +    def test_get_all_block_records(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_db_connector.py
> +def test_write_loan_states_to_db(self, db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_initializer_db_connector.py
> +    def initializer_db_connector(self):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_initializer_db_connector.py
> +        return InitializerDBConnector(db_url="sqlite:///:memory:")
don't use sqllite, just mock it

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_initializer_db_connector.py
> +    def test_get_zklend_by_user_ids(self, initializer_db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_initializer_db_connector.py
> +    def test_save_debt_category(self, initializer_db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_initializer_db_connector.py
> +    def test_get_zklend_by_user_ids_empty_result(self, initializer_db_connector):
add docstring and annotation type and return type

2024-10-25 20:57 UTC, djeck1432 commented on data_handler/tests/db_test/test_initializer_db_connector.py
> +    def test_save_debt_category_invalid_version(self, initializer_db_connector):
add docstring and annotation type and return type

2024-10-26 10:08 UTC, djeck1432 commented
@NueloSE Any update?

2024-10-26 16:10 UTC, djeck1432 commented
@NueloSE Please, fix all comments till tomorrow morning, thank you

2024-10-26 18:53 UTC, djeck1432 commented
@NueloSE Please, finish this task as soon as possible, this task blocking us to publish new issues, thank you for your understanding

2024-10-27 06:50 UTC, NueloSE commented
@djeck1432 am on it implement requested changes before end of today

2024-10-27 07:43 UTC, djeck1432 commented
@NueloSE Just checked your github, you are contributing to other project, others devs waiting when you finish this task. this task should be done today, otherwise I will be merge it and you will have just half of reward. 
Please, don't do that next time.

2024-10-27 19:02 UTC, closed without merging