Standardize event data for borrowing event
CarmineOptions/derisk-research pull request #241
Opened 2024-10-26 19:55 UTC by ikemHood

May fix #240 

- added BorrowingEventData model
- impl parsed event data in `parse_borrowing_event`

2024-10-26 20:28 UTC, djeck1432 requested changes
where is the last part?
In method [process_borrowing_event](https://github.com/CarmineOptions/derisk-research/blob/master/data_handler/handlers/loan_states/zklend/events.py#L281)
substitute fetching data by index Example: user= data[0] to data.user using serializer class

2024-10-27 17:35 UTC, djeck1432 requested changes
Please, fix merge conflict

2024-10-27 17:35 UTC, djeck1432 commented on data_handler/handlers/loan_states/zklend/events.py
> +        user = add_leading_zeros(event_data.user)
move this logic `add_leading_zeros` to Model level not here

2024-10-27 17:35 UTC, djeck1432 commented on data_handler/handlers/loan_states/zklend/events.py
> +        token = add_leading_zeros(event_data.token)
move this logic `add_leading_zeros` to Model level not here

2024-10-27 17:35 UTC, djeck1432 commented on data_handler/handlers/loan_states/zklend/events.py
> +        face_amount = decimal.Decimal(str(int(event_data.face_amount, base=16)))
move this logic `decimal.Decimal(str(int(event_data.face_amount, base=16)))` to Model level

2024-10-27 20:17 UTC, djeck1432 commented
@ikemHood Please, resolve conflicts

2024-10-27 21:22 UTC, ikemHood commented
Done

2024-10-28 15:59 UTC, merged