feat: Implement Withdrawal event
CarmineOptions/derisk-research pull request #247
Opened 2024-10-27 14:12 UTC by Mystic-Nayy

Resolves #233

2024-10-27 17:19 UTC, djeck1432 requested changes

2024-10-27 17:19 UTC, djeck1432 commented on get-pip.py
Why do we have this file here? 
Please remove it

2024-10-27 20:14 UTC, djeck1432 requested changes
Update also in `events.py` logic 
please, read issue description

2024-10-28 12:24 UTC, djeck1432 commented
@Mystic-Nayy Update also in events.py logic
please, read issue description
@Mystic-Nayy Please resolve conflict

2024-10-28 14:23 UTC, Mystic-Nayy commented
> @Mystic-Nayy Update also in events.py logic please, read issue description @Mystic-Nayy Please resolve conflict

I am on it sir

2024-10-28 15:56 UTC, djeck1432 commented
@Mystic-Nayy Update also in events.py logic
please, read issue description
@Mystic-Nayy Please resolve conflict

2024-10-29 12:35 UTC, djeck1432 requested changes
Looks good to me, resolve please conflict

2024-10-29 18:21 UTC, djeck1432 commented
@Mystic-Nayy Please, resolve conflict

2024-10-29 20:50 UTC, djeck1432 commented on data_handler/handler_tools/data_parser/zklend.py
> +        parsed_event = WithdrawalEventData(
remove this `parsed_event` and return directly `WithdrawalEventData`

2024-10-29 20:51 UTC, djeck1432 commented on data_handler/handler_tools/data_parser/serializers.py
> +class WithdrawalEventData(BaseModel):
add docstring

2024-10-29 20:51 UTC, djeck1432 requested changes
small issues

2024-10-29 20:51 UTC, djeck1432 commented
@Mystic-Nayy I resolved merge conflict, fix small issues

2024-10-29 21:05 UTC, djeck1432 commented
@Mystic-Nayy and please, tell me how did you test it?

2024-10-30 06:55 UTC, djeck1432 approved these changes
Looks good to me

2024-10-30 08:02 UTC, merged