feat: implement save zklend event to db
CarmineOptions/derisk-research pull request #264
Opened 2024-10-30 15:29 UTC by mayasimi

Fixes #258

2024-10-30 15:29 UTC, mayasimi commented
@djeck1432 ready for review

2024-10-30 16:00 UTC, mayasimi commented
@djeck1432 kindly review

2024-10-30 19:24 UTC, djeck1432 requested changes
Please, add also logic to fetch `ZkLend` address and block_number and send it to DersikApiConnector to finalize this task

2024-10-30 19:24 UTC, djeck1432 commented on apps/data_handler/handlers/events/zklend/transform_events.py
> +    def __init__(self):
add docstring please

2024-10-30 19:24 UTC, djeck1432 commented on apps/data_handler/handlers/events/zklend/transform_events.py
> +        self.db_connector.create_liquidation_event(db_model)
Please ,add `if __name__ == "__main__"` to test it

2024-10-30 21:48 UTC, djeck1432 commented
@mayasimi Please, add also logic to fetch ZkLend address and block_number and send it to DersikApiConnector to finalize this task

2024-10-31 06:01 UTC, mayasimi commented
> Please, add also logic to fetch `ZkLend` address and block_number and send it to DersikApiConnector to finalize this task

@djeck1432 where can i fetch the addresses and block numbers from

2024-10-31 12:11 UTC, djeck1432 requested changes

2024-10-31 12:11 UTC, djeck1432 commented on apps/data_handler/handlers/events/zklend/transform_events.py
> +    def __init__(self):
Add docstring please here.

2024-10-31 19:52 UTC, djeck1432 approved these changes
Looks good to me

2024-10-31 19:52 UTC, merged