adressing add pylint workflow and fix all issues
CarmineOptions/derisk-research pull request #268
Opened 2024-10-30 19:57 UTC by sigmadawg

addresses #262

2024-10-30 20:21 UTC, djeck1432 requested changes
Please, sync with master and don't remove any code

2024-10-30 20:21 UTC, djeck1432 commented on .github/workflows/pylint.yml
> +        python-version: '3.10'
we use `python3.11`

2024-10-30 20:21 UTC, djeck1432 commented on apps/data_handler/celery_app/tasks.py
> -# @app.task(name="run_loan_states_computation_for_hashtack_v0")
please, don't remove any code

2024-10-30 20:21 UTC, djeck1432 commented on apps/data_handler/celery_app/tasks.py
> -# from data_handler.handlers.loan_states.hashtack_v0.run import HashtackV0StateComputation
please, leave these imports

2024-10-30 20:21 UTC, djeck1432 commented on apps/data_handler/celery_app/tasks.py
> -# def run_loan_states_computation_for_hashtack_v1():
don't remove any code

2024-10-30 20:21 UTC, djeck1432 commented on apps/data_handler/celery_app/tasks.py
> -# @app.task(name="run_loan_states_computation_for_nostra_mainnet")
don't remove any code

2024-10-30 20:21 UTC, djeck1432 commented on apps/data_handler/db/models/loan_states.py
> +
you have duplicated code

2024-10-30 20:21 UTC, djeck1432 commented on apps/data_handler/handler_tools/constants.py
> -    "nostra::core::tokenization::lib::nostra_token::NostraTokenComponent::Burn": "process_debt_burn_event",
why did you remove this code?

2024-10-30 20:21 UTC, djeck1432 commented on apps/data_handler/handler_tools/nostra_alpha_settings.py
> -    # '0x0061d892cccf43daf73407194da9f0ea6dbece950bb24c50be2356444313a707',  # iWBTC
Don't remove any code, please!!!!

2024-10-30 20:59 UTC, closed without merging

2024-10-30 21:05 UTC, sigmadawg commented
sorry for the inconvenience, im a complete newbie, i tried linting the codes using black, but that didnt entirely fix all the long line issues, so i did some manually and messed up a lot.
If you allow then i will try again and just run the black command.

2024-10-31 12:12 UTC, djeck1432 commented
1. REad documentation how to use `black`
2. Apply only for files which you have changes, NOT For the whole project
3. @sigmadawg

2024-10-31 14:21 UTC, sigmadawg commented
> @sigmadawg If you're having issues, I could help work on it and put up a PR in One hour, if that's okay with you.
> 
> cc @djeck1432

Yes, i'd like the help