re-worked on #Add pylint workflow and fix all issues"
CarmineOptions/derisk-research pull request #269
Opened 2024-10-31 00:07 UTC by sigmadawg

addresses #262

2024-10-31 09:01 UTC, djeck1432 requested changes
It won't work this way with some text in dostring, it should contain description of the class/file/method/function not just some random text

2024-10-31 09:01 UTC, djeck1432 commented on apps/data_handler/handler_tools/__init__.py
> +"""Module docstring placeholder."""
It won't work this way, it should contain description of the file not just some random text

2024-10-31 09:01 UTC, djeck1432 commented on apps/data_handler/handler_tools/api_connector.py
> +"""Module docstring placeholder."""
It won't work this way, it should contain description of the file not just some random text

2024-10-31 09:01 UTC, djeck1432 commented on apps/data_handler/handler_tools/constants.py
> +"""Module docstring placeholder."""
It won't work this way, it should contain description of the file not just some random text

2024-10-31 09:01 UTC, djeck1432 commented on apps/data_handler/handler_tools/constants.py
> +    """class docstring"""
It won't work this way, it should contain description of the class not just some random text

2024-10-31 15:23 UTC, sigmadawg commented
@djeck1432 Could you kindly check if its alright now?

2024-10-31 20:12 UTC, djeck1432 requested changes
please, resolve merge conflict and revert removed field

2024-10-31 20:12 UTC, djeck1432 commented on apps/data_handler/db/schemas.py
> -    protocol_id: str
Why did you remove this field?

2024-10-31 22:13 UTC, sigmadawg commented
KIndly check

2024-10-31 22:28 UTC, sigmadawg commented
KIndly check

2024-11-01 07:58 UTC, djeck1432 approved these changes
THe biggest PR ever 116 files
looks good to me

2024-11-01 08:02 UTC, djeck1432 commented
@sigmadawg Please fix one test case and I will merge it

2024-11-01 09:09 UTC, sigmadawg commented
Kindly check
![image](https://github.com/user-attachments/assets/1c28e762-a58d-412f-8216-0df2a4ff384a)

2024-11-01 09:09 UTC, sigmadawg commented
is this okay?

2024-11-01 09:10 UTC, djeck1432 commented
@sigmadawg run pipeline, will see soon

2024-11-01 09:13 UTC, sigmadawg commented
I ran the workflow, attached the pictures above

2024-11-01 09:13 UTC, djeck1432 commented
@sigmadawg Pylint not passed
https://github.com/CarmineOptions/derisk-research/actions/runs/11626963851/job/32379739187?pr=269

2024-11-01 09:14 UTC, djeck1432 commented
did you sync with `master`? because I have another result
<img width="927" alt="Screenshot 2024-11-01 at 10 14 12" src="https://github.com/user-attachments/assets/1852b51c-0d0c-4f29-8c21-e72d28d61f6c">

2024-11-01 09:30 UTC, sigmadawg commented
Kindly check @djeck1432

2024-11-01 09:37 UTC, merged

2024-11-01 09:37 UTC, djeck1432 commented
@sigmadawg merged, passed

2024-11-01 09:38 UTC, sigmadawg commented
thankss!