feat/Zklend_models
CarmineOptions/derisk-research pull request #273
Opened 2024-10-31 12:38 UTC by binayak9932

Issue  #272 

- [X]   Created new models for missing events [here](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/zklend_events.py)Inherited from [EventBaseModel](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/db/models/event.py#L19C7-L19C21)
Created new models for next events:
- [X]  RepaymentEventData
- [X]  DepositEventData
- [X]  BorrowingEventData
- [X]  WithdrawalEventData
- [X]  CollateralEnabledDisabledEventData
- [X]  Generated migration file

2024-10-31 12:38 UTC, binayak9932 commented
@djeck1432  Please review

2024-10-31 19:27 UTC, djeck1432 requested changes
1. Rework migration file after your changes
2. Remove `poetry.lock` if you didn't do any changes in `pyproject.toml`

2024-10-31 19:27 UTC, djeck1432 commented on apps/data_handler/db/models/zklend_events.py
> +    __tablename__ = "repayment_event_data"
we don't need to have here `_data`. please remove it
`repayment_event` will be okay

2024-10-31 19:27 UTC, djeck1432 commented on apps/data_handler/db/models/zklend_events.py
> +    __tablename__ = "deposit_event_data"
we don't need to have here `_data`. please remove it
`deposit_event` will be okay

2024-10-31 19:27 UTC, djeck1432 commented on apps/data_handler/db/models/zklend_events.py
> +    __tablename__ = "borrowing_event_data"
we don't need to have here ` _data.` please remove it
`borrowing_event` will be okay

2024-10-31 19:27 UTC, djeck1432 commented on apps/data_handler/db/models/zklend_events.py
> +    __tablename__ = "withdrawal_event_data"
we don't need to have here  _data. please remove it
`withdrawal_event` will be okay

2024-10-31 19:27 UTC, djeck1432 commented on apps/data_handler/db/models/zklend_events.py
> +    __tablename__ = "collateral_enabled_disabled_event_data"
we don't need to have here `_data`. please remove it
`collateral_enabled_disabled_event` will be okay

2024-10-31 20:42 UTC, binayak9932 commented
@djeck1432  Please review

2024-10-31 20:52 UTC, binayak9932 commented
> 1. Rework migration file after your changes
> 2. Remove `poetry.lock` if you didn't do any changes in `pyproject.toml`

Done

2024-11-01 08:00 UTC, djeck1432 approved these changes
Looks good to me, good job

2024-11-01 08:01 UTC, merged