Added Web App workflow
CarmineOptions/derisk-research pull request #292
Opened 2024-11-21 16:36 UTC by Chukwuemeka-James

2024-11-21 20:22 UTC, djeck1432 requested changes
Add `.env.test` to populate telegram creds to pretend error there

2024-11-22 13:15 UTC, djeck1432 requested changes
You still have the same error, please fix that

https://github.com/Chukwuemeka-James/derisk-research/actions/runs/11962413333/job/33350769876

2024-11-23 14:31 UTC, djeck1432 commented
@Chukwuemeka-James Any progres?

2024-11-23 17:58 UTC, djeck1432 requested changes

2024-11-23 17:58 UTC, djeck1432 commented on .github/workflows/wep_app_ci.yml
> +on: [push, pull_request]
```suggestion
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```

2024-11-23 19:57 UTC, djeck1432 commented
@Chukwuemeka-James Any progress?

2024-11-23 20:04 UTC, Chukwuemeka-James commented
I'm just seeing this right now. I'll implement the suggested changes and
create a PR. Thank you for your patience 🙏🏿.

On Sat, 23 Nov 2024, 20:57 djeck1432, ***@***.***> wrote:

> @Chukwuemeka-James <https://github.com/Chukwuemeka-James> Any progress?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CarmineOptions/derisk-research/pull/292#issuecomment-2495637184>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BI3KIAA5U6RKNB2ZFYUSKST2CDM23AVCNFSM6AAAAABSHNP2A2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJVGYZTOMJYGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-24 16:37 UTC, djeck1432 requested changes

2024-11-24 16:37 UTC, djeck1432 commented on .github/workflows/wep_app_ci.yml
> +on: [push, pull_request]
why you didn't fix that?

2024-11-24 16:37 UTC, djeck1432 commented on .github/workflows/wep_app_ci.yml
> +      - name: Install dependencies for Shared
why do you need here shared?

2024-11-24 16:37 UTC, djeck1432 commented on .github/workflows/wep_app_ci.yml
> +      - name: Run Tests for Shared
Why do you need here run for shared?

2024-11-25 16:42 UTC, djeck1432 commented
@Chukwuemeka-James Any updates?

2024-11-26 17:27 UTC, djeck1432 approved these changes
Looks good to me

2024-11-26 17:28 UTC, merged