Tasks for processing and storing ZkLend protocol events
CarmineOptions/derisk-research pull request #295
Opened 2024-11-22 06:55 UTC by Benjtalkshow

#291  Draft
@djeck1432 , This is a draft PR

2024-11-22 08:31 UTC, djeck1432 requested changes
add executing task here
https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/celery_app/celery_conf.py

2024-11-22 08:31 UTC, djeck1432 commented on apps/data_handler/celery_app/event_tasks.py
> +if __name__ == "__main__":
remove this one, it's not needed here

2024-11-22 09:29 UTC, Benjtalkshow commented
> add executing task here https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/celery_app/celery_conf.py

yea. still working on it

2024-11-22 09:29 UTC, Benjtalkshow commented on apps/data_handler/celery_app/event_tasks.py
> +if __name__ == "__main__":
Alright. Thanks

2024-11-22 19:29 UTC, djeck1432 commented
@Benjtalkshow Any updates?

2024-11-22 19:56 UTC, Benjtalkshow commented
> @Benjtalkshow Any updates?

Yes, i am trying to run `pylint`

2024-11-22 19:56 UTC, Benjtalkshow commented
> @Benjtalkshow Any updates?

Yes, i am trying to run `pylint`

2024-11-22 20:09 UTC, Benjtalkshow commented
I have updated my PR 
And made more changes according to this:
![image](https://github.com/user-attachments/assets/0915fc5f-f76b-4ac6-8316-d62e4022a975)

2024-11-23 10:22 UTC, djeck1432 approved these changes
Looks good

2024-11-23 10:23 UTC, merged