feat/issue-#288 fix
CarmineOptions/derisk-research pull request #301
Opened 2024-11-23 11:39 UTC by ekumamatthew

feat/issu-#288 fix for test_zklend_initializer

2024-11-23 14:09 UTC, djeck1432 requested changes

2024-11-23 14:09 UTC, djeck1432 commented on apps/data_handler/tests/conftest.py
> +      mock_initializer_connector.engine = MagicMock()
Please, fix spacing

2024-11-23 15:12 UTC, djeck1432 commented
@ekumamatthew Please, sync with `master` branch

2024-11-23 19:53 UTC, djeck1432 commented
<img width="697" alt="Screenshot 2024-11-23 at 20 53 32" src="https://github.com/user-attachments/assets/53626389-2eb2-44e5-a414-310fd0e02522">
Do you need help to sync with master?

2024-11-23 19:53 UTC, djeck1432 commented
@ekumamatthew

2024-11-23 20:00 UTC, ekumamatthew commented
It's in sync with master.

2024-11-24 05:53 UTC, ekumamatthew commented
I'm closing this issue because i opened a new PR  https://github.com/CarmineOptions/derisk-research/pull/306 .

2024-11-24 05:54 UTC, closed without merging