feat: standardize event data for mint and burn none-interest
CarmineOptions/derisk-research pull request #305
Opened 2024-11-24 02:26 UTC by Tzienom

Closes #285

2024-11-24 11:13 UTC, djeck1432 commented on apps/data_handler/handlers/loan_states/nostra_alpha/events.py
> +        if self.ZERO_ADDRESS in {sender, recipient} | self.ZERO_ADDRESS in {parsed_event.sender, parsed_event.recipient}:
why diid you change this code?

2024-11-24 11:14 UTC, djeck1432 commented on apps/data_handler/handlers/loan_states/nostra_alpha/events.py
> +        if parsed_event.sender != self.DEFERRED_BATCH_CALL_ADAPTER_ADDRESS:
You have duplicated code, please remove it

2024-11-24 11:15 UTC, djeck1432 commented
@Tzienom I'm not sure that you can manage with this task, so easy task and so many issues

2024-11-24 11:47 UTC, Tzienom commented
i will fix it before end of day

2024-11-24 16:05 UTC, djeck1432 requested changes
Okay, last attempt, please, do not override main logic, you just need to substitute parsing event["data"] with your parser and use these fields

2024-11-24 16:05 UTC, djeck1432 commented on apps/data_handler/handlers/loan_states/nostra_alpha/events.py
>              sender = add_leading_zeros(event["data"][0])
why you didn't remove these fields?

2024-11-24 16:05 UTC, djeck1432 commented on apps/data_handler/handlers/loan_states/nostra_alpha/events.py
> +        if user == self.IGNORE_USER | parsed_event == self.IGNORE_USER:
why did you change this code?
and why parsed event return only user data here if it should return more values?

2024-11-24 16:05 UTC, djeck1432 commented on apps/data_handler/handlers/loan_states/nostra_alpha/events.py
> +        if user == self.verbose_user | parsed_event.user == self.verbose_user:
why did you change it

2024-11-25 13:45 UTC, djeck1432 commented
@Tzienom Please fix your comments within next hours, otherwise you will be unassigned, this task blocking us to go further

2024-11-25 15:04 UTC, Tzienom commented
completing shortly

2024-11-25 16:42 UTC, djeck1432 requested changes
Please, sync with master

2024-11-25 17:52 UTC, Tzienom commented
@djeck1432 my branch is currently uptodate with master already

2024-11-25 23:54 UTC, closed without merging