Feat/set up fastapi project
CarmineOptions/derisk-research pull request #70
Opened 2024-04-24 10:34 UTC by iamnovichek

>   1. `.gitignore` added
>   2. `docker-compose` and `dockerfile` for running project in the docker added
>   3.  `README` file with description `how to set up and run the project` added
>   4. `.env.example` file added
>   5. `db_manager` for db connection added
>   6. poetry for package manager added

2024-04-24 11:41 UTC, djeck1432 requested changes

2024-04-24 11:41 UTC, djeck1432 commented on web_app/README.md
> +
add please description for current variables in `.env.example`

2024-04-24 11:41 UTC, djeck1432 commented on web_app/README.md
> +cd derisk
It should be `web_app`

2024-04-24 11:41 UTC, djeck1432 commented on web_app/README.md
> +Create `.env` file or just rename `.env.example` --> `.env`
It could be done as a command `mv .env.example .env` 
Please add it here

2024-04-24 11:41 UTC, djeck1432 commented on web_app/README.md
> +```
Please, add command, how you can stop it
`docker-compose stop`

2024-04-24 11:41 UTC, djeck1432 commented on web_app/database/database.py
> +def get_database() -> SessionLocal:
Please, add docstring to this func

2024-04-26 18:05 UTC, iamnovichek commented
closed by mistake

2024-04-26 18:06 UTC, iamnovichek commented
closed by mistake

2024-04-26 19:01 UTC, djeck1432 approved these changes

2024-04-29 12:26 UTC, merged